### ISSUE TITLE
Any chance you update to TF 1.2.1

### ISSUE THREAD

**Issue by the-holger** [Thunderbottom/Tensorflow-macOS-binary#1]
Hey!

After getting a headache trying to figure out how to prepare the environment for compiling TF myself I stumbled on your repo. Is there any chance you might provide an updated version (currently 1.2.1 is stable I think) of the package?

Thanks!
Holger

**Comment by Thunderbottom** [comment]
I'm sorry, have been a lot busy lately. I'll update today!

**Comment by Thunderbottom** [comment]
Updated to [`tensorflow 1.3.0`](https://github.com/tensorflow/tensorflow/releases/tag/v1.3.0) in c7966423765ac8d426f8a6939681ebbff6035103
